---
# tasks file for nginx

 - name: Installation de epel-release
   yum:
    name: epel-release
    state: present

 - name: Installer nginx
   yum:
    name: nginx
    state: present

 - name : Copier le fichier nginx.conf vers la machine cible sous /etc/nginx/nginx.conf
   copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

 - name: Créer les répertoires /var/www/konoha.local & /var/www/suna.local
   file:
    path: "/var/www/{{ item }}/html"
    state: directory
    owner: root
    group: root
    recurse: yes
   loop:
    "{{ sites }}"

 - name: Modification des autorisations sur le répertoire /var/www
   file:
    path: /var/www
    owner: root
    group: root
    mode: '0755'
    recurse: yes

 - name: "Création du fichier index.html sous /var/www/{{ sites }}/html"
   template:
     src: "index.j2"
     dest: "/var/www/{{ item }}/html/index.html"
   loop:
     "{{ sites }}"

 - name: Creation des répertoires pour les hôtes virtuels
   file:
    state: directory
    path: "/etc/nginx/sites-{{ item }}"
    owner: root
    group: root
   loop:
    "{{ dossiers_sites_nginx }}" 

 - name: "Insertion de la ligne include /etc/nginx/sites-enabled/*.conf; dans le fichier nginx.conf"
   lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: "^# Settings"
    line: "    include /etc/nginx/sites-enabled/*.conf;"
 
 - name: "Création des fichiers /etc/nginx/sites-available/{{ sites }}.conf"
   template:
    src: "default.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: root
   loop:
    "{{ sites }}"

 - name: "Creation des liens symbolics pour /etc/nginx/sites-available/{{ sites }}.conf & /etc/nginx/sites-available/{{ sites }}.conf"
   file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    owner: root
    group: root
    state: link
   loop:
     "{{ sites }}"

 - name: "Redémarrer le service nginx"
   systemd:
    name: nginx
    state: restarted
    enabled: yes

 - name: "ouvrir le port 80/http"
   firewalld:
    service: http
    permanent: yes
    state: enabled

 - name: "recharger le firewalld"
   systemd:
    name: firewalld
    state: reloaded   
