---
- name: installation du package Mariadb
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: redémarrage du service Mariadb
  systemd:
    name: mariadb
    enabled: yes
    state: restarted

- name: démarrage de mysql_secure_installation
  command: 'echo "& y y Mypasswd Mypasswd y y y y" | ./usr/bin/mysql_secure_installation'
